Feature responsive profile
BlackStone8960/Musician-First pull request #116
Opened 2022-01-26 08:44 UTC by YumiKimbara

Created responsive profile page

2022-01-26 23:47 UTC, miyabitanimchi reviewed
@YumiKimbara Thank you so much Yumi, it looks great! And I think it's ok for Galaxy Fold.
I just left one comment below, so please check when you can!

2022-01-26 23:47 UTC, miyabitanimchi commented on src/styles/components/_profile.scss
> +}
I thought the left and right padding 5% is a good idea, but for now many parts are based on px, so could you change `5%` to `15px` ? 🙏
If it's ok, could you create `_variables.scss` in `styles/abstracts` and create a variable for the padding-x so we can import and use the same value `15px` to anywhere needed?

2022-01-27 00:49 UTC, Kit486759 requested changes
Thank you for the changes, Yumi!

![image](https://user-images.githubusercontent.com/76936712/151270217-1dbf7797-efba-4918-aa0c-2c11fa9662db.png)
Email and Spotify link cropped in mobile size, how will it be like in actual phone? 

![image](https://user-images.githubusercontent.com/76936712/151270477-dc7d1f1d-bd21-496e-af7c-156c206c7e3d.png)
There are some off for the buttons, could you please adjust it?

2022-01-30 08:27 UTC, YumiKimbara commented on src/styles/components/_profile.scss
> +}
Thank you for checking! I fixed it, so could you check it again?

2022-01-30 08:29 UTC, YumiKimbara commented
@Kit486759 Thank you for checking!
>Email and Spotify link cropped in mobile size, how will it be like in actual phone?
As I discuss Alex, I will keep as it is so far :)

>There are some off for the buttons, could you please adjust it?
Sorry I completely missed it, and I fixed it, so could you check it again?

2022-01-30 23:20 UTC, Kit486759 approved these changes
Thank you for the fix @YumiKimbara. It works well.

2022-01-31 03:49 UTC, miyabitanimchi reviewed
Thank you so much for fixing @YumiKimbara ! 
I'm sorry😭, I also missed this but we will have the additional button below when we login with your email(not gmail), so we need responsive design for this case as well.
So could you also work on it? 🙏
![スクリーンショット 2022-01-30 午後7 24 46](https://user-images.githubusercontent.com/69213541/151736197-27192997-8aae-4f38-a2be-e257aadfb48d.jpg)


Also, I left one comment below about `_variables.scss` so please check it as well.
Thank you in advance!

2022-01-31 03:49 UTC, miyabitanimchi commented on src/styles/abstracts/_variables.scss
> +}
```suggestion
$responsive-px: 15px;
```

Thank you for creating `_variables.scss`🙂🙏 But I meant to create a variable something like this, so could you change it and import the variable to `_profile.scss` instead of having the class `.responsive-padding`?

2022-02-07 09:23 UTC, YumiKimbara commented on src/styles/abstracts/_variables.scss
> +}
Sorry for my misunderstanding, and not sure If I fixed correctly, but could you check it again?

2022-02-07 20:52 UTC, miyabitanimchi approved these changes
@YumiKimbara Thank you so much Yumi for fixing, just see the comment below, after you add `0` for padding top and bottom, you can merge this branch to `develop`. 👍

2022-02-07 20:52 UTC, miyabitanimchi commented on src/styles/components/_profile.scss
> +}
```suggestion
.responsive-px {
  padding: 0 $responsivePx;
}
```

Just add 0 here for padding top and bottom, like the one we had earlier.

2022-02-08 08:43 UTC, YumiKimbara commented on src/styles/components/_profile.scss
> +}
Thank you for checking! I fixed it, and will merge soon :)

2022-02-08 08:46 UTC, merged