Firebase data structure
BlackStone8960/Musician-First pull request #120
Opened 2022-02-12 00:20 UTC by Kit486759

Hi all, I made the function and data structure for embedding Youtube, Soundcloud and some adjust for Spotify.
It's just for desktop only for now.
Please use the project **"musician-first-copy"** in the firebase database to run this.
Thank you!

2022-02-12 21:18 UTC, BlackStone8960 commented on src/components/filter/Filter1.js
>    const btnRotate = (angle) => {
Could you delete the part you commented out?

2022-02-12 21:21 UTC, BlackStone8960 commented on src/components/userAccount/ProfileForm.js
> +  // };
Could you delete here, too?

2022-02-12 21:29 UTC, BlackStone8960 commented
Thank you for your update Kit, I tried to embed YouTube movie, but the error as following picture appeared.

<img width="672" alt="Screen Shot 2022-02-12 at 1 26 44 PM" src="https://user-images.githubusercontent.com/60183777/153728994-08d7971c-6135-44cf-aad6-a8a0cc1e851f.png">

Could you solve this problem? The link I embedded is as below.
<iframe width="560" height="315" src="https://www.youtube.com/embed/mHP6-D-yBEw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

2022-02-12 21:43 UTC, BlackStone8960 commented on src/components/MusicianPage/MusicPlayer.js
> +  const [width, setWidth] = useState(290);
Maybe you can use constants to define unique values like this. These unique values in the code are called "Magic Number", and this can cause confusion for the reader of the code. You can refer this article when you have time: https://jeffreyeverhart.com/2020/09/28/javascript-tips-using-named-constants-for-magic-numbers/

2022-02-12 21:46 UTC, BlackStone8960 commented on src/components/MusicianPage/SoundCloud.js
> +        }}
Can you make sure that the code for the styles is written in Sass?

2022-02-12 21:55 UTC, BlackStone8960 requested changes
Thank you for your update Kit, I tried to embed YouTube movie, but the error as following picture appeared.

<img width="672" alt="Screen Shot 2022-02-12 at 1 26 44 PM" src="https://user-images.githubusercontent.com/60183777/153729720-5588e286-fad3-472e-8f42-87304ab6cd35.png">

Could you solve this problem? The link I embedded is as below.

`<iframe width="560" height="315" src="https://www.youtube.com/embed/mHP6-D-yBEw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

Also, there are conflicts between this branch and the develop branch.
Could you resolve it when you push new code as well?

Thank you!

2022-02-13 23:24 UTC, Kit486759 commented on src/components/filter/Filter1.js
>    const btnRotate = (angle) => {
I clean it.

2022-02-13 23:25 UTC, Kit486759 commented on src/components/MusicianPage/MusicPlayer.js
> +    }
fixed it. thank you!

2022-02-14 18:33 UTC, YumiKimbara commented
I think everything is working fine! Could you just add `cursor: pointer;` on each help button?

2022-02-15 00:21 UTC, Kit486759 commented
> cursor: pointer;

Thanks @YumiKimbara  , that have been fixed.

2022-02-17 05:48 UTC, YumiKimbara commented
@Kit486759 Thank you so much for fixing it!!

2022-02-18 19:19 UTC, miyabitanimchi approved these changes
@Kit486759 Sorry for my late check, it looks great, thank you for improving the code!

2022-02-18 19:24 UTC, BlackStone8960 commented on src/components/MusicianPage/MusicPlayer.js
> +  const CENTER_EMBED_WIDTH = 240;
Can you declare constants outside component if you can? Because these processes will run every time component refreshes.

2022-02-18 19:33 UTC, BlackStone8960 commented
Hi @Kit486759 , sorry for the late check, and thank you so much for rewriting code. Code looks great and I could embed youtube movie as well, but I noticed one little thing so could you kindly read and respond it when you have time? Thank you.

2022-02-19 04:55 UTC, BlackStone8960 approved these changes
Thank you for fixing it, it looks so good now!

2022-02-19 07:43 UTC, merged